plugins {
    id 'java'
    id 'idea'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}

group 'fybug.nulll'
version '0.0.4'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(23)
    }
}

repositories {
    mavenLocal()
    mavenCentral()
    google()
    maven { url 'https://repo.spring.io/milestone' }
    maven { url 'https://repo.spring.io/snapshot' }
    maven { url "https://repo.spring.io/milestone" }
    maven { url 'https://maven.aliyun.com/repository/releases' }
    maven { url "https://maven.aliyun.com/repository/jcenter" }
    maven { url "https://maven.aliyun.com/repository/mapr-public" }
    maven { url "https://maven.aliyun.com/repository/staging-alpha" }
    maven { url "https://maven.aliyun.com/repository/central" }
    maven { url "https://maven.aliyun.com/repository/public/" }
    maven { url "https://maven.aliyun.com/repository/google" }
    maven { url "https://maven.aliyun.com/repository/gradle-plugin" }
    maven { url "https://maven.aliyun.com/repository/spring" }
    maven { url "https://maven.aliyun.com/repository/spring-plugin" }
    maven { url "https://maven.aliyun.com/repository/grails-core" }
    maven { url "https://maven.aliyun.com/repository/snapshots" }
    maven { url "https://maven.aliyun.com/repository/apache-snapshots" }
    maven { url "https://maven.aliyun.com/repository/staging-alpha-group" }
}

dependencies {
    implementation fileTree(dir: 'lib', includes: ['*.jar'])

    compileOnly "org.jetbrains:annotations:+"
    annotationProcessor "org.jetbrains:annotations:+"

    testImplementation 'junit:junit:4.13.1'
    testCompileOnly "org.jetbrains:annotations:+"
    testAnnotationProcessor "org.jetbrains:annotations:+"
}

tasks.register('PDFunctionLibrary', Jar) {
    destinationDirectory = file('jar')
    manifest {
        attributes(
                'Manifest-Version': '1.0',
                'Built-By': 'fybug/风雨bu改',
                'Created-By': 'IntelliJ IDEA'
        )
    }
    archiveFileName = 'PDF.jar'
    // 打包编译输出
    from sourceSets.main.output
}

tasks.register('PDFunctionLibrary_all', Jar) {
    destinationDirectory = file('jar')
    manifest {
        attributes(
                'Manifest-Version': '1.0',
                'Built-By': 'fybug/风雨bu改',
                'Created-By': 'IntelliJ IDEA'
        )
    }
    archiveFileName = 'PDF_all.jar'
    // 打包编译输出
    from sourceSets.main.output
    // 打包源码
    from sourceSets.main.allSource
}

tasks.register('PDFunctionLibrary_sources', Jar) {
    destinationDirectory = file('jar')
    manifest {
        attributes(
                'Manifest-Version': '1.0',
                'Built-By': 'fybug/风雨bu改',
                'Created-By': 'IntelliJ IDEA'
        )
    }
    archiveFileName = 'PDF_sources.jar'
    // 打包源码
    from sourceSets.main.allSource
}

tasks.register('release') {
    dependsOn clean
    dependsOn PDFunctionLibrary_all
    dependsOn PDFunctionLibrary
    dependsOn PDFunctionLibrary_sources
}